[package]
name = "ljenks-chess"
version = "0.0.1"
authors = ["starqi <helloimzirui@gmail.com>"]
edition = "2021"

[features]
my_debug = [] # Project verbosity toggle
default = ["dep:rand"] # For cargo check, tests, language server, but NEITHER WASM or CLI
# Then remove default features and pick one of the two below for real targets
wasm = ["wasm-bindgen", "console_error_panic_hook", "my_debug"]
cli = ["dep:rand"]

[lib]
crate-type = ["cdylib", "rlib"] # Can target both WASM and native, even though currently it's just WASM

[[bin]]
name = "chess-cli"
path = "src/main.rs"
require-features = ["cli"] # Makes no sense for WASM target due to file system access

[dependencies]
wasm-bindgen = { version = "0.2.92", optional = true }
lazy_static = "1.5.0"
rand = { version = "0.8.5", optional = true }
clap = { version = "4.5", features = ["derive"] }

# The `console_error_panic_hook` crate provides better debugging of panics by
# logging them with `console.error`. This is great for development, but requires
# all the `std::fmt` and `std::panicking` infrastructure, so isn't great for
# code size when deploying.
console_error_panic_hook = { version = "0.1.7", optional = true }

[dev-dependencies]
wasm-bindgen-test = "0.3.42" # TODO What is this?

[profile.release]
opt-level = 3

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[profile.dev]
debug = true
debug-assertions = true
overflow-checks = true
panic = 'unwind'
incremental = true
