# Worker values: "half", "full", or int

# Common
batch_size: 16000 # TODO IMMEDIATE Understand the SparseAdam problem more
lr: 0.002
checkpoint_path: main.checkpoint
loader_num_workers: "full" # 5


# train_once.py
positions_path: xyz.bin # 8mill.bin
simple_epochs: 100 # 3


# repeat_train.py
cycles: 100
epochs_per_cycle: 3
games_per_worker: 50 # 11,000
games_per_worker_validation_set: 25
workers: "full"

# TODO IMMEDIATE Update this when it becomes more clear what is going on
# INTUITION: Need shallow depth, never train with mega high depth.
# NN cannot capture e.g. depth 20 "superintelligence" but it can capture
# risk like bishops and queens lined up against the king.

max_nodes: 30000
random_half_moves: 15
max_half_moves: 200
val_every: 1
validation_path: validation.bin
checkpoint_backup_count: 2
sigmoid_scale: 400
